#!/bin/bash

set -e

debug='false'
gdb='false'
copyvideo='false'
fpga='false'

while getopts 'dgvf' flag; do
  case "${flag}" in
    d) debug='true' ;;
    g) gdb='true' ;;
    v) copyvideo='true' ;;
    f) fpga='true' ;;
    *) exit 1 ;;
  esac
done
shift $((OPTIND -1))

if [ "$1" == "" ]; then
  echo "Usage: remote_make FOLDER"
  exit 1
fi

# The folder to copy
FOLDER=$1
BASENAME=`basename $FOLDER`
# Remove this argument
shift

echo "Copying files..."
if [ $fpga == "true" ]; then
  rsync -ru $FOLDER a405-15.enst.fr:/cal/exterieurs/ext5100/src/
else
  rsync -ru $FOLDER odroid:/home/odroid/src/
fi
# scp -r $FOLDER odroid:/home/odroid/src/


# echo "Removing old binaries..."
# ssh odroid "cd /home/odroid/src/$BASENAME && make clean"

echo "Compiling..."
if [ $fpga == "true" ]; then
  ssh a405-15.enst.fr "cd /cal/exterieurs/ext5100/src/$BASENAME"
else
  ssh odroid "cd /home/odroid/src/$BASENAME && make"
fi

if [ $debug == "true" ]; then
  echo "Executing in debug mode..."
  ssh odroid "cd /home/odroid/src/$BASENAME && LD_LIBRARY_PATH=/opt/ComputeLibrary/build make debug"
elif [ $gdb == "true" ]; then
  echo "Executing on gdb..."
  ssh -t odroid "cd /home/odroid/src/$BASENAME && LD_LIBRARY_PATH=/opt/ComputeLibrary/build gdb $BASENAME $@"
elif [ $fpga == "true" ]; then
  echo "Executing fpga..."
  ssh -t a405-15.enst.fr "cd /cal/exterieurs/ext5100/src/$BASENAME && ./setup.sh && make cl_compile && make sim"
else 
  echo "Executing..."
  ssh odroid "cd /home/odroid/src/$BASENAME && LD_LIBRARY_PATH=/opt/ComputeLibrary/build ./$BASENAME"
fi


if [ $copyvideo == "true" ]; then
  scp odroid:src/$BASENAME/output.avi $FOLDER
fi
